import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import { ToastProvider } from "@/frontend/contexts/toast/provider";
import { ProfileDataProvider } from "@/frontend/contexts/profileData/provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased bg-background`}
      >
        <ToastProvider>
          <ProfileDataProvider>
            {children}
          </ProfileDataProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
